config/routes.rb
Rails.application.routes.draw do
  # Login page
  match 'login' => 'auth#login', via: [:get, :post]
  delete 'login' => 'auth#logout'

  # Ping
  post 'ping' => 'pings#create'

  # User
  resource :user, only: [:show, :edit, :update]
  get 'user-flair' => 'users#flair', format: 'jpg'

  # Friendships
  resources :friendships, path: 'following'

  # Timeline
  get 'network' => 'timeline_entries#index', as: :network
  delete 'network/incoming' => 'timeline_entries#hide_all_incoming'
  delete 'network/:id' => 'timeline_entries#destroy', as: :timeline_entry
  get 'network/incoming' => 'timeline_entries#incoming', as: :incoming_network

  # Remote posts
  get 'remote/:url' => 'posts#remote', as: :remote_post, constraints: { url: /.+/ }

  # Tag pages
  get 'tag/:tag' => 'posts#tagged', as: :tagged_posts
  get 'tag/all/:tag' => 'posts#tagged', as: :all_tagged_posts, all: 1

  # Daily archives
  get ':year/:month/:day' => 'posts#day', as: :day,
    constraints: { year: /\d+/, month: /\d+/, day: /\d+/ }

  # Server Administration
  get 'server' => 'server#dashboard'
  namespace :server do
    resources :users
    resources :pings
  end

  # API Discovery
  get 'pants' => 'application#discovery', format: [:json], as: :discovery

  # Legacy
  get '/posts/:id' => 'posts#show'
  get ':year-:month-:day' => redirect("/%{year}/%{month}/%{day}")
  get '/friends' => redirect("/following")
  get '/timeline' => redirect("/network")
  get '/timeline/incoming' => redirect("/network/incoming")
  get '/timeline/all' => redirect("/network/incoming")

  # Primary posts resource
  resources :posts, only: [:index, :create]
  resources :posts, path: '', except: [:index, :create]

  # /
  root to: 'posts#index'

  # catch-all route for 404s
  match '*splat', to: 'application#render_404', via: [:get, :post, :delete, :put], format: [:html]
end

app/models/timeline_entry.rb
class TimelineEntry < ActiveRecord::Base
  validates_presence_of :user_id, :post_id

  belongs_to :user
  belongs_to :post

  scope :from_friends, -> { where(from_friend: true) }
  scope :from_others,  -> { where(from_friend: false) }
  scope :hidden,       -> { where(hidden: true) }
  scope :visible,      -> { where(hidden: false) }
end

app/controllers/timeline_entries_controller.rb
class TimelineEntriesController < ApplicationController
  load_and_authorize_resource :timeline_entry,
    through: :current_site

  # Enable AJAX and JSON
  respond_to :js, :json

  before_filter(only: [:index, :incoming]) do
    @timeline_entries = @timeline_entries
      .visible
      .includes(:post)
      .order('timeline_entries.created_at DESC')
      .limit(20)
  end

  def index
    @timeline_entries = @timeline_entries.from_friends
    respond_with @timeline_entries
  end

  def incoming
    @timeline_entries = @timeline_entries.from_others
    respond_with @timeline_entries
  end

  def destroy
    @timeline_entry.update_attributes(hidden: true)
    respond_with @timeline_entry
  end

  def hide_all_incoming
    @timeline_entries.from_others
      .where('timeline_entries.created_at <= ?', Time.at(params.require(:until).to_i + 1))
      .update_all(hidden: true)

    redirect_to :network, notice: "All available incoming posts have been hidden."
  end
end

app/views/timeline_entries/_more.html.slim
- entries = @timeline_entries.page(params[:page]).per(20)
= render entries
p#more-posts
  = link_to_next_page entries, "Load more posts", remote: true

app/views/timeline_entries/_timeline_entry.html.slim
= div_for timeline_entry, class: timeline_entry.from_friend? ? 'from-friend' : 'from-other' do

  - if action_name == 'incoming'
    - content_for :extra_post_actions, flush: true do
      li.post-hide-link = link_to 'Hide', timeline_entry, method: 'delete', remote: true
      - if timeline_entry.post.user.present?
        li.post-add-friend-link = link_to 'Follow', friendships_path(friend: { url: timeline_entry.post.user.domain}), method: 'post'

  = render timeline_entry.post

app/views/timeline_entries/incoming.html.slim
- if @timeline_entries.any?
  .note These posts have been pushed to you from new followers.
        How about following them back? You can also #{link_to "hide all of these posts", incoming_network_path(until: @timeline_entries.first.created_at.to_i), method: 'delete', data: { confirm: "Are you sure?" }}.

  = render 'more'

app/views/timeline_entries/index.html.slim
- if can? :create, Post
  = render 'posts/miniform', post: Post.new

- incoming_users = current_site.timeline_entries.visible.from_others.joins(:post).count('DISTINCT posts.domain')
- if incoming_users > 0
  .incoming-notice You have #{link_to "incoming posts", :incoming_network} from
                   #{pluralize incoming_users, "new follower"}.

= render 'more'